[2023-04-28T04:33:38.344+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: stock_analyzer.delete_file_task manual__2023-04-28T04:33:22.757207+00:00 [queued]>
[2023-04-28T04:33:38.369+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: stock_analyzer.delete_file_task manual__2023-04-28T04:33:22.757207+00:00 [queued]>
[2023-04-28T04:33:38.371+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T04:33:38.373+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-04-28T04:33:38.374+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T04:33:38.413+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): delete_file_task> on 2023-04-28 04:33:22.757207+00:00
[2023-04-28T04:33:38.425+0000] {standard_task_runner.py:55} INFO - Started process 517 to run task
[2023-04-28T04:33:38.432+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'stock_analyzer', 'delete_file_task', 'manual__2023-04-28T04:33:22.757207+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp1j_fonuh']
[2023-04-28T04:33:38.434+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask delete_file_task
[2023-04-28T04:33:38.552+0000] {task_command.py:388} INFO - Running <TaskInstance: stock_analyzer.delete_file_task manual__2023-04-28T04:33:22.757207+00:00 [running]> on host 501f01ebf2a1
[2023-04-28T04:33:38.645+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_analyzer
AIRFLOW_CTX_TASK_ID=delete_file_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T04:33:22.757207+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T04:33:22.757207+00:00
[2023-04-28T04:33:38.645+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: delete_file() missing 1 required positional argument: 'delete_file_path'
[2023-04-28T04:33:38.659+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=stock_analyzer, task_id=delete_file_task, execution_date=20230428T043322, start_date=20230428T043338, end_date=20230428T043338
[2023-04-28T04:33:38.679+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task delete_file_task (delete_file() missing 1 required positional argument: 'delete_file_path'; 517)
[2023-04-28T04:33:38.734+0000] {local_task_job.py:208} INFO - Task exited with return code 1
